
spring:
  application:
    name: web-example
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB

server:
  port: 8882

swagger-info:
  title: web-example
  description: web示例
  version: 2025.3.0
  base-package: com.plasticene.boot.example.web.controller
  url: https://www.shepherd126.top/
  author: shepherd
  email: shepherd_zfj@163.com
ptc:
  api:
    log:
      enable: false

    security:
      enable: true
      rsa-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDtUiTm53YKJXHVlzjTXSlL5Ajd/8p33Wy71pYCP/U2SIPNZ+3lX8LUKh2PFLLxr9RCtJAA7wGWtDbiywDe/2I90ZOGUUfIExPShv2wRCbSwMRtdcKYnUD78/ZCl2FKSKjOlbzFbBjIX5qLTk557+xNj72F7jlqGqW8KEFSHFykowyNmicWdjGjjYg6n1ylejwt/T47rFh22xzfo7fcffS4LxgbLzwR7fvbMhgl1tyog66idsY4iyAGhUAf+Waifxqtdo6SeIMSks0AzGJuIbPvPN2GkHHoiAScjQlu71QMCEznlgHotuYBsy/kMksi6ok5i1ygFdkDF92aetmOllbtAgMBAAECggEACjSHfIJxjTTxzmlTutfju1OE0H8VmgGK+BAQ07hXKn/Q/L4LLEG2ia1+wRtdXCh4355CHwT05yHvkxSygErJ7IMDOm039MuVOG79Oio3Sfk0hfx6L/Phl02oLLiAj4aZjVPbeHKrvvOvHDraA9y99AV9W35uBTkJU99rR6uk9DnIt1Ajgp10068s92Ube8chaCMoppuKh9bgJ1KWKK/TEvu4OwjeXMoINY1GDP4+SSsEUQeN9fyXwLMjV89scvKorglMFZSe/18azALjafNP2leteRnGqVQ800WbvQxb3EQSUULQbEu3VDm5sWRTzg7FbPXFQdcR81euZYHC1DDRQQKBgQD1zlwX6EhlISpyiH1izd3+DZPHAFrvUsGN2cUp6V/p3Sr7zE6LKmiVTOJxpf09f5XEw9GwE01H4Tj/GaoTW7ejNtca/GLabZdmJBBC1xOFAqT/4JRUw7voL1+ICllgPMFG+gTAdexLwwBIIg98HarrJMJCf9rXEOuL5ZBTA0GU0QKBgQD3KbMhHbQy+uks5gfqnCoiGyDZz/K1X8eo4CinH5M1foZ2R0Gm44ZTyksJG3J+v3BUzNWKWddPzrPle5EWMxNeVDKB6diQIxMBIZUY2KpaFeUBDx3M0KwV7kFz2lbmniPjc7SHkMFfAW7EFas6ys4wgBV6KLQF4yCf8ATt0DyXXQKBgCvvYKKdUCNTVET4hIDejylTv/A37gkM36+9FvKw1gX1FDPBhuB1ChB1l5v8sVEGtvxei+JO8OdCKG/gZHflUuOHb9dQ+VJVeFQ3afiofMKvgFKED78+5R1RKmAkiWkcMue+1I6aBUxdZHWAMQhcPSqefWJpe/IpAhEVTUCpOlWhAoGAKLv9orqThUdnAJhUu6zLIN3ZtywXcx769/EhohGJIGre3EV4I3oiHFMdtL2KTCte5wrvMqMF4khNy8dmrQLz8TrtLA4PPAobyrbvLK4gvUIYgOkt3yCRC/g9X0ufwNhVT9o06ZbI19CToct0cfcUrledsolcyg+Zw+I53bvREJ0CgYEAgIRvdP2vKa3g9v039b8eo+ZPxExKYo6Ld+1hfWVY4rg4Mo/Yv9KcTq2ohYjCoKvb09eVYlQIEmmzNGR9eDnEpQCErx9NzxC2p9q36YvABBlrr3iL4ORg01IE1wL1usi/UxU/fT1dzHLHFyf/TXxuUouh1h+8EVqvgQSfAneKsNI=
      rsa-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7VIk5ud2CiVx1Zc4010pS+QI3f/Kd91su9aWAj/1NkiDzWft5V/C1CodjxSy8a/UQrSQAO8BlrQ24ssA3v9iPdGThlFHyBMT0ob9sEQm0sDEbXXCmJ1A+/P2QpdhSkiozpW8xWwYyF+ai05Oee/sTY+9he45ahqlvChBUhxcpKMMjZonFnYxo42IOp9cpXo8Lf0+O6xYdtsc36O33H30uC8YGy88Ee372zIYJdbcqIOuonbGOIsgBoVAH/lmon8arXaOkniDEpLNAMxibiGz7zzdhpBx6IgEnI0Jbu9UDAhM55YB6LbmAbMv5DJLIuqJOYtcoBXZAxfdmnrZjpZW7QIDAQAB





