server:
  port: 8884


spring:
  application:
    name: plasticene-boot-mybatis-example
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.10.0.18:3306/ptc_flow?&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true&useInformationSchema=true
logging:
  level:
    com.plasticene.boot.example.mybatis: debug

ptc:
  encrypt:
    algorithm: aes
    key: plasticene666666
    # 必须16位
    iv: plasticene666666

#  tenant:
#    enable: true
