<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>plasticene-boot-starter-parent</artifactId>
        <groupId>com.plasticene.boot</groupId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>


    <artifactId>plasticene-boot-starter-web</artifactId>


    <dependencies>
        <dependency>
            <groupId>com.plasticene.boot</groupId>
            <artifactId>plasticene-common</artifactId>
        </dependency>

        <!-- web  -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- knife4.5.0对应boot是3.2.3→spring web6.1+  但boot3.4.5→spring web6.2.6
             导致ControllerAdviceBean不一致报错，knife4j页面加载不出来，所以单独处理下
             等后续knife4j版本升级适配此处再升级即可-->
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springdoc</groupId>
                    <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.8.7</version>
        </dependency>

        <dependency>
            <groupId>com.plasticene.boot</groupId>
            <artifactId>plasticene-boot-starter-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>

        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
        </dependency>






    </dependencies>

</project>